import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Delete existing entries
  await knex('bookings').del();

  // Insert seed entries
  await knex('bookings').insert([
    {
      id: 'booking-1',
      booking_number: 'URB-2024-001',
      renter_id: 'user-1',
      owner_id: 'user-2',
      product_id: 'product-1',
      start_date: '2024-12-01',
      end_date: '2024-12-03',
      status: 'confirmed',
      payment_status: 'completed',
      insurance_type: 'standard',
      pickup_method: 'pickup',
      pickup_address: 'KG 123 St, Kacyiru',
      delivery_address: null,
      pickup_coordinates: JSON.stringify({ lat: -1.9441, lng: 30.0619 }),
      delivery_coordinates: null,
      insurance_policy_number: 'INS-001-2024',
      insurance_premium: 25000,
      insurance_details: JSON.stringify({ coverage: 'standard', deductible: 50000 }),
      base_amount: 500000,
      total_amount: 525000,
      security_deposit: 100000,
      platform_fee: 25000,
      tax_amount: 0,
      ai_risk_score: 0.15,
      ai_assessment: JSON.stringify({ risk_level: 'low', factors: ['verified_user', 'good_history'] }),
      special_instructions: 'Please ensure the villa is clean and ready for check-in at 2 PM',
      renter_notes: 'Looking forward to a great vacation!',
      owner_notes: 'Guest seems reliable, confirmed payment received',
      admin_notes: null,
      initial_condition: 'excellent',
      final_condition: null,
      damage_report: null,
      damage_photos: null,
      timeline: JSON.stringify([
        { event: 'booking_created', timestamp: '2024-11-15T10:00:00Z', user_id: 'user-1' },
        { event: 'payment_completed', timestamp: '2024-11-15T10:30:00Z', user_id: 'user-1' },
        { event: 'booking_confirmed', timestamp: '2024-11-15T11:00:00Z', user_id: 'user-2' }
      ]),
      features: JSON.stringify(['wifi', 'pool', 'parking']),
      location: JSON.stringify({ lat: -1.9441, lng: 30.0619 }),
      pickup_methods: JSON.stringify(['pickup']),
      pickup_time: '14:00:00',
      return_time: '11:00:00',
      specifications: JSON.stringify({ guests: 4, duration: 2 }),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      id: 'booking-2',
      booking_number: 'URB-2024-002',
      renter_id: 'user-6',
      owner_id: 'user-7',
      product_id: 'product-2',
      start_date: '2024-12-05',
      end_date: '2024-12-07',
      status: 'pending',
      payment_status: 'pending',
      insurance_type: 'premium',
      pickup_method: 'pickup',
      pickup_address: 'KG 456 St, Kimisagara',
      delivery_address: null,
      pickup_coordinates: JSON.stringify({ lat: -1.9441, lng: 30.0619 }),
      delivery_coordinates: null,
      insurance_policy_number: null,
      insurance_premium: 15000,
      insurance_details: JSON.stringify({ coverage: 'premium', deductible: 25000 }),
      base_amount: 90000,
      total_amount: 105000,
      security_deposit: 50000,
      platform_fee: 5000,
      tax_amount: 0,
      ai_risk_score: 0.25,
      ai_assessment: JSON.stringify({ risk_level: 'medium', factors: ['new_user', 'unverified_phone'] }),
      special_instructions: 'Car should be clean and have full tank',
      renter_notes: 'First time renting, excited!',
      owner_notes: 'New user, will monitor closely',
      admin_notes: null,
      initial_condition: null,
      final_condition: null,
      damage_report: null,
      damage_photos: null,
      timeline: JSON.stringify([
        { event: 'booking_created', timestamp: '2024-11-20T14:00:00Z', user_id: 'user-6' },
        { event: 'payment_pending', timestamp: '2024-11-20T14:00:00Z', user_id: 'user-6' }
      ]),
      features: JSON.stringify(['air_conditioning', 'bluetooth']),
      location: JSON.stringify({ lat: -1.9441, lng: 30.0619 }),
      pickup_methods: JSON.stringify(['pickup']),
      pickup_time: '09:00:00',
      return_time: '17:00:00',
      specifications: JSON.stringify({ passengers: 2, duration: 2 }),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      id: 'booking-3',
      booking_number: 'URB-2024-003',
      renter_id: 'user-1',
      owner_id: 'user-2',
      product_id: 'product-3',
      start_date: '2024-11-25',
      end_date: '2024-11-26',
      status: 'completed',
      payment_status: 'completed',
      insurance_type: 'standard',
      pickup_method: 'delivery',
      pickup_address: null,
      delivery_address: 'KG 789 St, Kacyiru',
      pickup_coordinates: null,
      delivery_coordinates: JSON.stringify({ lat: -1.9441, lng: 30.0619 }),
      insurance_policy_number: 'INS-002-2024',
      insurance_premium: 20000,
      insurance_details: JSON.stringify({ coverage: 'standard', deductible: 30000 }),
      base_amount: 150000,
      total_amount: 170000,
      security_deposit: 75000,
      platform_fee: 7500,
      tax_amount: 0,
      ai_risk_score: 0.10,
      ai_assessment: JSON.stringify({ risk_level: 'low', factors: ['verified_user', 'repeat_customer'] }),
      special_instructions: 'Handle with care, professional equipment',
      renter_notes: 'Great for wedding photography',
      owner_notes: 'Excellent customer, always returns equipment in good condition',
      admin_notes: null,
      initial_condition: 'excellent',
      final_condition: 'excellent',
      damage_report: null,
      damage_photos: null,
      timeline: JSON.stringify([
        { event: 'booking_created', timestamp: '2024-11-20T09:00:00Z', user_id: 'user-1' },
        { event: 'payment_completed', timestamp: '2024-11-20T09:15:00Z', user_id: 'user-1' },
        { event: 'booking_confirmed', timestamp: '2024-11-20T09:30:00Z', user_id: 'user-2' },
        { event: 'delivery_started', timestamp: '2024-11-25T08:00:00Z', user_id: 'user-2' },
        { event: 'delivery_completed', timestamp: '2024-11-25T08:30:00Z', user_id: 'user-2' },
        { event: 'pickup_started', timestamp: '2024-11-26T18:00:00Z', user_id: 'user-2' },
        { event: 'booking_completed', timestamp: '2024-11-26T18:30:00Z', user_id: 'user-2' }
      ]),
      features: JSON.stringify(['professional_grade', 'complete_kit']),
      location: JSON.stringify({ lat: -1.9441, lng: 30.0619 }),
      pickup_methods: JSON.stringify(['delivery']),
      pickup_time: '08:00:00',
      return_time: '18:00:00',
      specifications: JSON.stringify({ event_type: 'wedding', duration: 1 }),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    }
  ]);

  console.log('✅ Bookings seeded successfully');
}
