import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Delete existing entries
  await knex('payment_transactions').del();

  // Insert seed entries
  await knex('payment_transactions').insert([
    {
      id: 'payment-1',
      booking_id: 'booking-1',
      user_id: 'user-1',
      payment_method_id: null,
      transaction_type: 'booking_payment',
      amount: 525000,
      currency: 'RWF',
      provider: 'mtn_momo',
      provider_transaction_id: 'MTN-001-2024',
      provider_fee: 5250,
      status: 'completed',
      processed_at: knex.fn.now(),
      expires_at: null,
      original_currency: null,
      original_amount: null,
      exchange_rate: null,
      exchange_rate_date: null,
      metadata: JSON.stringify({ booking_number: 'URB-2024-001', payment_method: 'mobile_money' }),
      failure_reason: null,
      provider_response: JSON.stringify({ status: 'success', reference: 'MTN-001-2024' }),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: 'user-1',
      updated_by: 'system'
    },
    {
      id: 'payment-2',
      booking_id: 'booking-2',
      user_id: 'user-6',
      payment_method_id: null,
      transaction_type: 'booking_payment',
      amount: 105000,
      currency: 'RWF',
      provider: 'airtel_money',
      provider_transaction_id: null,
      provider_fee: 1050,
      status: 'pending',
      processed_at: null,
      expires_at: knex.raw("NOW() + INTERVAL '24 hours'"),
      original_currency: null,
      original_amount: null,
      exchange_rate: null,
      exchange_rate_date: null,
      metadata: JSON.stringify({ booking_number: 'URB-2024-002', payment_method: 'mobile_money' }),
      failure_reason: null,
      provider_response: null,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: 'user-6',
      updated_by: 'user-6'
    },
    {
      id: 'payment-3',
      booking_id: 'booking-3',
      user_id: 'user-1',
      payment_method_id: null,
      transaction_type: 'booking_payment',
      amount: 170000,
      currency: 'RWF',
      provider: 'mtn_momo',
      provider_transaction_id: 'MTN-002-2024',
      provider_fee: 1700,
      status: 'completed',
      processed_at: knex.fn.now(),
      expires_at: null,
      original_currency: null,
      original_amount: null,
      exchange_rate: null,
      exchange_rate_date: null,
      metadata: JSON.stringify({ booking_number: 'URB-2024-003', payment_method: 'mobile_money' }),
      failure_reason: null,
      provider_response: JSON.stringify({ status: 'success', reference: 'MTN-002-2024' }),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: 'user-1',
      updated_by: 'system'
    },
    {
      id: 'payment-4',
      booking_id: 'booking-1',
      user_id: 'user-1',
      payment_method_id: null,
      transaction_type: 'security_deposit',
      amount: 100000,
      currency: 'RWF',
      provider: 'mtn_momo',
      provider_transaction_id: 'MTN-003-2024',
      provider_fee: 1000,
      status: 'completed',
      processed_at: knex.fn.now(),
      expires_at: null,
      original_currency: null,
      original_amount: null,
      exchange_rate: null,
      exchange_rate_date: null,
      metadata: JSON.stringify({ booking_number: 'URB-2024-001', deposit_type: 'security' }),
      failure_reason: null,
      provider_response: JSON.stringify({ status: 'success', reference: 'MTN-003-2024' }),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: 'user-1',
      updated_by: 'system'
    },
    {
      id: 'payment-5',
      booking_id: 'booking-3',
      user_id: 'user-1',
      payment_method_id: null,
      transaction_type: 'refund',
      amount: 75000,
      currency: 'RWF',
      provider: 'mtn_momo',
      provider_transaction_id: 'MTN-004-2024',
      provider_fee: 750,
      status: 'completed',
      processed_at: knex.fn.now(),
      expires_at: null,
      original_currency: null,
      original_amount: null,
      exchange_rate: null,
      exchange_rate_date: null,
      metadata: JSON.stringify({ booking_number: 'URB-2024-003', refund_type: 'security_deposit' }),
      failure_reason: null,
      provider_response: JSON.stringify({ status: 'success', reference: 'MTN-004-2024' }),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: 'system',
      updated_by: 'system'
    }
  ]);

  console.log('✅ Payment transactions seeded successfully');
}
