import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Delete existing entries
  await knex('user_verifications').del();

  // Insert seed entries
  await knex('user_verifications').insert([
    {
      id: 'verification-1',
      user_id: 'user-1',
      verification_type: 'kyc',
      document_type: 'national_id',
      document_number: '1199001234567890',
      document_image_url: 'https://example.com/documents/user1_id.jpg',
      address_line: 'KG 123 St, Kacyiru',
      city: 'Kigali',
      district: 'rw-kigali-gasabo',
      country: 'RW',
      selfie_image_url: 'https://example.com/selfies/user1_selfie.jpg',
      ocr_data: JSON.stringify({ name: 'John Doe', id_number: '1199001234567890' }),
      liveness_score: 0.95,
      ai_profile_score: 0.88,
      verification_status: 'verified',
      verified_by: 'user-3',
      verified_at: knex.fn.now(),
      notes: 'All documents verified successfully',
      ai_processing_status: 'completed',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      id: 'verification-2',
      user_id: 'user-2',
      verification_type: 'kyc',
      document_type: 'national_id',
      document_number: '1199002345678901',
      document_image_url: 'https://example.com/documents/user2_id.jpg',
      address_line: 'KN 456 St, Huye',
      city: 'Huye',
      district: 'rw-south-huye',
      country: 'RW',
      selfie_image_url: 'https://example.com/selfies/user2_selfie.jpg',
      ocr_data: JSON.stringify({ name: 'Jane Smith', id_number: '1199002345678901' }),
      liveness_score: 0.92,
      ai_profile_score: 0.91,
      verification_status: 'verified',
      verified_by: 'user-3',
      verified_at: knex.fn.now(),
      notes: 'Business owner verification completed',
      ai_processing_status: 'completed',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      id: 'verification-3',
      user_id: 'user-3',
      verification_type: 'kyc',
      document_type: 'national_id',
      document_number: '1199003456789012',
      document_image_url: 'https://example.com/documents/user3_id.jpg',
      address_line: 'KG 789 St, Kimisagara',
      city: 'Kigali',
      district: 'rw-kigali-nyarugenge',
      country: 'RW',
      selfie_image_url: 'https://example.com/selfies/user3_selfie.jpg',
      ocr_data: JSON.stringify({ name: 'Admin User', id_number: '1199003456789012' }),
      liveness_score: 0.98,
      ai_profile_score: 0.95,
      verification_status: 'verified',
      verified_by: 'system',
      verified_at: knex.fn.now(),
      notes: 'Admin account verification',
      ai_processing_status: 'completed',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      id: 'verification-4',
      user_id: 'user-4',
      verification_type: 'kyc',
      document_type: 'national_id',
      document_number: '1199004567890123',
      document_image_url: 'https://example.com/documents/user4_id.jpg',
      address_line: 'KG 321 St, Rubavu',
      city: 'Rubavu',
      district: 'rw-west-rubavu',
      country: 'RW',
      selfie_image_url: 'https://example.com/selfies/user4_selfie.jpg',
      ocr_data: JSON.stringify({ name: 'Moderator User', id_number: '1199004567890123' }),
      liveness_score: 0.94,
      ai_profile_score: 0.89,
      verification_status: 'verified',
      verified_by: 'user-3',
      verified_at: knex.fn.now(),
      notes: 'Moderator verification completed',
      ai_processing_status: 'completed',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      id: 'verification-5',
      user_id: 'user-5',
      verification_type: 'kyc',
      document_type: 'national_id',
      document_number: '1199005678901234',
      document_image_url: 'https://example.com/documents/user5_id.jpg',
      address_line: 'KG 654 St, Musanze',
      city: 'Musanze',
      district: 'rw-north-musanze',
      country: 'RW',
      selfie_image_url: 'https://example.com/selfies/user5_selfie.jpg',
      ocr_data: JSON.stringify({ name: 'Inspector User', id_number: '1199005678901234' }),
      liveness_score: 0.96,
      ai_profile_score: 0.93,
      verification_status: 'verified',
      verified_by: 'user-3',
      verified_at: knex.fn.now(),
      notes: 'Professional inspector verification',
      ai_processing_status: 'completed',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      id: 'verification-6',
      user_id: 'user-6',
      verification_type: 'kyc',
      document_type: 'national_id',
      document_number: '1199006789012345',
      document_image_url: 'https://example.com/documents/user6_id.jpg',
      address_line: 'KG 987 St, Kayonza',
      city: 'Kayonza',
      district: 'rw-east-kayonza',
      country: 'RW',
      selfie_image_url: 'https://example.com/selfies/user6_selfie.jpg',
      ocr_data: JSON.stringify({ name: 'Mary Wilson', id_number: '1199006789012345' }),
      liveness_score: 0.87,
      ai_profile_score: 0.82,
      verification_status: 'pending',
      verified_by: null,
      verified_at: null,
      notes: 'Student verification pending review',
      ai_processing_status: 'processing',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      id: 'verification-7',
      user_id: 'user-7',
      verification_type: 'kyc',
      document_type: 'national_id',
      document_number: '1199007890123456',
      document_image_url: 'https://example.com/documents/user7_id.jpg',
      address_line: 'KG 147 St, Karongi',
      city: 'Karongi',
      district: 'rw-west-karongi',
      country: 'RW',
      selfie_image_url: 'https://example.com/selfies/user7_selfie.jpg',
      ocr_data: JSON.stringify({ name: 'David Brown', id_number: '1199007890123456' }),
      liveness_score: 0.91,
      ai_profile_score: 0.87,
      verification_status: 'verified',
      verified_by: 'user-3',
      verified_at: knex.fn.now(),
      notes: 'Business owner verification completed',
      ai_processing_status: 'completed',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      id: 'verification-8',
      user_id: 'user-8',
      verification_type: 'kyc',
      document_type: 'national_id',
      document_number: '1199008901234567',
      document_image_url: 'https://example.com/documents/user8_id.jpg',
      address_line: 'KG 258 St, Muhanga',
      city: 'Muhanga',
      district: 'rw-south-muhanga',
      country: 'RW',
      selfie_image_url: 'https://example.com/selfies/user8_selfie.jpg',
      ocr_data: JSON.stringify({ name: 'Sarah Jones', id_number: '1199008901234567' }),
      liveness_score: 0.83,
      ai_profile_score: 0.78,
      verification_status: 'rejected',
      verified_by: 'user-3',
      verified_at: knex.fn.now(),
      notes: 'Document quality insufficient, please resubmit',
      ai_processing_status: 'completed',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    }
  ]);

  console.log('✅ User verifications seeded successfully');
}
